version: '3.8'

services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: npm start
    restart: always
